### ISSUE TITLE
How to build on Mac

### ISSUE THREAD

**Issue by StevanovicNina** [MultiCraft/MultiCraft-legacy#202]
I just got MultiCraft - Build And Mine! on my MacBook Pro from my MacBook Pro App Store, but I cannot build anything, and the Use key (which I changed to Control) does nothing. How do I build things? Is there a button that I am missing? Is it supposed to be free on the App Store? Thank you very much in advance! #202

**Comment by MoNTE48** [comment]
You can use two-finger tap to place block...

**Comment by StevanovicNina** [comment]
I cannot do a two-finger tap on my MacBook Pro, maybe because it only has one built-in mouse pad. Can I change something so that I can place a block somehow else?

**Comment by MoNTE48** [comment]
![](https://cdn.osxdaily.com/wp-content/uploads/2019/05/mac-right-click-two-finger-secondary-click-trackpad-610x339.jpg)

**Comment by StevanovicNina** [comment]
I tried that, but that does not work. Can I change something so that I can place a block somehow else?

**Comment by ozmugatu** [comment]
I was having same issue. On macbook air. After a few tries, I figured out that a gentle two finger tap works just fine. Hope this helps anyone else with same issue.

**Comment by pascal-103** [comment]
thanks
