### ISSUE TITLE
How to build android on MacOS

### ISSUE THREAD

**Issue by takaaptech** [MultiCraft/MultiCraft-legacy#210]
Hi
I try to download and run ./Start.sh inside build/android folder but I have this error
=> Creating Assets:
cp: native/deps/Android/Irrlicht/shaders: No such file or directory

Please help! Thank you so much!

**Comment by MoNTE48** [comment]
Use gradle build first.

**Comment by takaaptech** [comment]
@MoNTE48 Thank you so much!
